### PR TITLE
v7.0.0 pre-Berlin HF Release

### PR DESCRIPTION
**Pull request by holgerd77**
Ok, I am through. 😄 

@winsvega Totally wasn't aware on all the updates which happened here throughout the last months, writing a CHANGELOG here makes one really aware of all the great work being done, congrats!

Thank you also for the new change log write-up, this helped a lot on preparation.

### CODE REVIEW

**Comment by holgerd77** [comment]
Can this be merged? I think it would be nice to have a pre-Berlin release as reference point for development before https://github.com/ethereum/tests/pull/685 gets merged.

**Comment by winsvega** [comment]
I am making an update. please one moment.

**Comment by winsvega** [comment]
ah. its too big. ok better include it into next release.

**Comment by holgerd77** [comment]
@winsvega Ok, thanks so much! Have now released this as a [v7.0.0](https://github.com/ethereum/tests/releases/tag/v7.0.0) tagged release on GitHub and also posted on [Reddit](https://www.reddit.com/r/ethereum/comments/gk6g5g/v700_preberlin_hf_release_for_ethereum_consensus/).

**Pull request merged**
