### PR TITLE
Add Tests to Verify No Refunds Occur when Contract Creation runs Out of Gas

### PR DESCRIPTION
**Pull request by marioevz**
Add checks for ethereumjs/ethereumjs-monorepo#1603 using the following test cases:
- Create from EOA/CREATE/CREATE2, Sstore Refund in Init Code, OoG on Code Deposit and Invalid opcode
- Create from EOA/CREATE/CREATE2, Sstore Refund in Call, OoG on Code Deposit and Invalid opcode
- Create from EOA/CREATE/CREATE2, Sstore Refund in DelegateCall, OoG on Code Deposit and Invalid opcode
- Create from EOA/CREATE/CREATE2, Sstore Refund in CallCode, OoG on Code Deposit and Invalid opcode
- Create from EOA/CREATE/CREATE2, Refund in Self-destruct call, OoG on Code Deposit and Invalid opcode
- Create from EOA/CREATE/CREATE2, Refund within CREATE, OoG on Code Deposit and Invalid opcode
- Create from EOA/CREATE/CREATE2, Refund within CREATE2, OoG on Code Deposit and Invalid opcode
- Create from EOA/CREATE/CREATE2, Log within CREATE, OoG on Code Deposit and Invalid opcode

Edit: Added more test cases using CREATE/2

### CODE REVIEW

**Comment by jochem-brouwer** [comment]
That's fast :smile: Great! :+1:

**Comment by jochem-brouwer** [comment]
Just ran our VM against this branch, all pass except one, CreateOOGFromEOARefunds_d13g0v0_London. This is because we do not clear selfdestructs in case of not enough gas for code deposits.

We probably also have this issue with logs. Could you add one more test where you essentially do the same as CreateOOGFromEOARefunds_d13g0v0_London, but instead of the selfdestruct, log an event in the creation code.

**Comment by marioevz** [comment]
Hi @jochem-brouwer, I uploaded the other test cases you required, could you check if this hits the code path you needed? Thanks!

**Comment by jochem-brouwer** [comment]
Hi @marioevz, had to explicitly check if these tests hit the "codestore out of gas" and not "normal" execution OOGs and it does - this indeed covers the test coverage which was needed. Thanks a lot! :smile: So from my side this is now complete!

**Pull request merged**
