### PR TITLE
Add GeneralStateTests/stEWASMTests placeholder

### PR DESCRIPTION
**Pull request by axic**
Required by https://github.com/ethereum/cpp-ethereum/pull/4764

### CODE REVIEW

**Comment by axic** [comment]
cc @winsvega @jwasinger

**Comment by winsvega** [comment]
what is this?

**Comment by axic** [comment]
Created a directory for the tests so that the cpp-ethereum change can be merged. It is a wasm specific test suite.

**Comment by axic** [comment]
@winsvega this should be mergeable now

**Comment by jwasinger** [comment]
So the only purpose of this is to make cpp-ethereum build pass right?  Because we have moved the actual working branch for our eWasm tests to here: https://github.com/ewasm/tests/tree/wasm-tests

**Comment by axic** [comment]
Explanation here: https://github.com/ethereum/cpp-ethereum/pull/4764#issuecomment-359413015

**Comment by pirapira** [comment]
The cpp-ethereum PR has been merged.

**Comment by pirapira** [comment]
But the cpp-ethereum PR has a different commit ID for ethereum/tests.  What's going on?

**Comment by axic** [comment]
@winsvega have created a duplicate PR of this and force pushed his commit over the cpp-ethereum PR.

**Comment by pirapira** [comment]
@axic oh, I see.  That's because Travis on `cpp-ethereum` cannot pull `axic/tests:ewasm`.

**Comment by pirapira** [comment]
I think @winsvega should have kept the original commits (with the original authors) when he created the new PR.

**Comment by axic** [comment]
> That's because Travis on cpp-ethereum cannot pull axic/tests:ewasm.

Yep, it was tested locally. Just needed to merge this PR and would have pushed a final commit into the cpp-ethereum PR.

**Comment by winsvega** [comment]
this PR had like 0 changes. 

```
0  GeneralStateTests/stEWASMTests/.gitkeep
No changes.
View  
0  src/GeneralStateTestsFiller/stEWASMTests/.gitkeep
No changes.
```

**Comment by axic** [comment]
It was the exact same change as you added with #401, just created a week prior.

**Pull request closed without merging**
