### PR TITLE
add vm test for arithmetic (add) after byte

### PR DESCRIPTION
**Pull request by jwasinger**
Designed to catch issues like https://github.com/ethereumjs/ethereumjs-vm/pull/293

### CODE REVIEW

**Comment by axic** [comment]
Would it make sense to have a script generate test cases bases on the arithmetic/logic/bitwise instruction list and their in/out arguments? The generator would need to combine at least two of those instructions in a single test case. We could also nominate `add` to be always the second op.

**Comment by pirapira** [comment]
@axic those tests are welcome.  It sounds like those tests take some space in the tests repo but they should run quite fast.

**Comment by winsvega** [comment]
not via RPC on cpp they not

**Comment by winsvega** [comment]
I guess we could come to a general test source format from which you just generate blockchain tests and vm tests.

**Comment by winsvega** [comment]
@qbzzt need to review the OP issue and possibly cover with the test cases

**Pull request merged**
