### PR TITLE
MultiSelfdestructedFiller: remove duplicated nonce field

### PR DESCRIPTION
**Pull request by MariusVanDerWijden**
Removes a duplicated field from the test

### CODE REVIEW

**Review by marioevz — APPROVED** [review]
LGTM

**Comment by winsvega** [comment]
ah wait. yml allows dublicates?

**Comment by MariusVanDerWijden** [comment]
No, duplicates are invalid according to the yaml spec https://yaml.org/spec/1.2-old/spec.html#id2764044

**Comment by winsvega** [comment]
huh, yaml-cpp allows it. strange. pushing a fix 

https://github.com/ethereum/tests/pull/1202

should not happen again.

**Pull request merged**
