### PR TITLE
Tutorials integrated into sphinx

### PR DESCRIPTION
**Pull request by qbzzt**
1. Retesteth tutorial
2. State transition tutorial (Solidity included)

### CODE REVIEW

**Comment by qbzzt** [comment]
I'm going to obsolete the old tutorial when I have the blockchain tutorial done (my next pull request, probably).

**Comment by winsvega** [comment]
check that sphinx make html is working without warnings. 
and that it look fine in html format

**Comment by qbzzt** [comment]
I did that before I submitted the pull request and made some changes based
on that.

**Comment by qbzzt** [comment]
You are right, there is a warning. I will remove the file from the PR.

**Comment by qbzzt** [comment]
Sorry, it turns out I fixed some issues but didn't commit. I will close the
pull request and create a new one when I commit

**Pull request closed without merging**
