### PR TITLE
Move creation tests to validation tests

### PR DESCRIPTION
**Pull request by hugo-dc**
Previous tests validating EOF by creating using CREATE/CREATE2/CreateTransaction were moved to the EOF Validation test format, as it is no longer valid EOF creation using the previous legacy methods.

### CODE REVIEW

**Comment by winsvega** [comment]
```
Test Case "stEIP3540": (8 of 13)
Error: Compiled test folder contains tests without Filler: 
 /home/travis/build/ethereum/tests/EIPTests/BlockchainTests/StateTests/stEOF/stEIP3540/CREATE2_EOF1Invalid_FromEOF.json
 /home/travis/build/ethereum/tests/EIPTests/BlockchainTests/StateTests/stEOF/stEIP3540/CreateTransactionInvalidEOF1.json
```

The generated tests need to be moved too

**Comment by hugo-dc** [comment]
Removed Blockchain tests without fillers.

**Comment by gumb0** [comment]
@hugo-dc Please rebase.

**Comment by hugo-dc** [comment]
Rebased

**Comment by gumb0** [comment]
`stEOF/ori/CreateEOF1Filler.yml` source removed, blockchain test removed, but `CreateEOF1.json` is not removed.
(Why no CI warning about this?)

**Comment by gumb0** [comment]
Same about `stEIP3670/CREATE2_EOF1Invalid_FromEOF` and `stEIP3670/CREATE_EOF1Invalid_FromEOF`

**Comment by gumb0** [comment]
I just deleted those leftover files, @hugo-dc please check

**Comment by hugo-dc** [comment]
> I just deleted those leftover files, @hugo-dc please check

It looks good now.

> (Why no CI warning about this?)

Usually retesteth itself catches json files without fillers when running the tests (not filling), I was double checking by doing that but somehow it didn't reported these files.

Another difference I see is that the BlockchainTest `EIPTests/BlockchainTests/StateTests/stEOF/stEIP4200/EOF1_RJUMP_RJUMPI_RJUMPV_Execution.json` is being modified even though the original yaml file was not changed. The change seems to be in the `excessBlobGas`, from `0x060000` to `0x00`.

**Review by gumb0 — APPROVED** [review]

**Comment by gumb0** [comment]
@winsvega This is ready to go from our side, please review.

**Comment by winsvega** [comment]
it should be 0x060000  in genesis now. it is a minor correction for the state tests to have 0 in the first block in its blockchain tests form the genesis value must be 60000

**Pull request merged**
