### PR TITLE
EIP-2315 changes in gascosts and update opcode

### PR DESCRIPTION
**Pull request by matkt**
- Changes in gascosts (https://github.com/ethereum/EIPs/pull/2676)

  - JUMPSUB -> 10 (high tier gas cost)
  - RETURNSUB -> 5 (low tier gas cost)
  - BEGINSUB -> 2 (base tier gas cost)

- Update opcode (https://github.com/ethereum/EIPs/pull/2682)

  - 0x5c BEGINSUB
  - 0x5d RETURNSUB
  - 0x5e JUMPSUB

- Add also a new test to prevent that a JUMPSUB can jump to a JUMPDEST. The new opcode must have its own valid jump table (ref https://github.com/ethereumjs/ethereumjs-vm/pull/754#discussion_r430875606)

Generated with Besu : https://github.com/hyperledger/besu/pull/995

### CODE REVIEW

**Comment by holgerd77** [comment]
Just asking - without too much insight: there were substantially more test files on the original subroutine test PR https://github.com/ethereum/tests/pull/685, were the ones missing not touched by the gas cost changes?

**Comment by matkt** [comment]
> Just asking - without too much insight: there were substantially more test files on the original subroutine test PR #685, were the ones missing not touched by the gas cost changes?

these are the ones that test failed transactions because when a transaction fails, all of the gas available for that transaction (gas limit) is sent to the miner. So the tests will not change

**Comment by winsvega** [comment]
please update all stSubroutine tests. the previous PR merged was not refilled. 
the HF defenition is updated in travis on tests::develop

**Comment by matkt** [comment]
> please update all stSubroutine tests. the previous PR merged was not refilled.
> the HF defenition is updated in travis on tests::develop

I regenerated the tests with the latest opcodes. I may have missed something. What do you mean by update?

**Comment by winsvega** [comment]
> > please update all stSubroutine tests. the previous PR merged was not refilled.
> > the HF defenition is updated in travis on tests::develop
> 
> I regenerated the tests with the latest opcodes. I may have missed something. What do you mean by update?

save all the test fillers. rebase on tests develop. paste test fillers back and run filltests command.

**Comment by matkt** [comment]
> > > please update all stSubroutine tests. the previous PR merged was not refilled.
> > > the HF defenition is updated in travis on tests::develop
> > 
> > 
> > I regenerated the tests with the latest opcodes. I may have missed something. What do you mean by update?
> 
> save all the test fillers. rebase on tests develop. paste test fillers back and run filltests command.

Thanks, Done

**Comment by winsvega** [comment]
hm. travis report errors. did you run 
` -t GeneralStateTests/stSubroutine -- --filltests` 
` -t GeneralStateTests/stSubroutine -- --filltests --fillchain` 
?

**Comment by matkt** [comment]
> hm. travis report errors. did you run
> ` -t GeneralStateTests/stSubroutine -- --filltests`
> ` -t GeneralStateTests/stSubroutine -- --filltests --fillchain`
> ?

Yes I'm doing 
`./retesteth -t GeneralStateTests/stSubroutine -- --filltests --fillchain`
And after
`./retesteth -t GeneralStateTests/stSubroutine -- --filltests  `

**Comment by matkt** [comment]
> hm. travis report errors. did you run
> ` -t GeneralStateTests/stSubroutine -- --filltests`
> ` -t GeneralStateTests/stSubroutine -- --filltests --fillchain`
> ?

It's strange because when I compare the value of `HashSrc`with the filler content, it's the same 😕

**Comment by winsvega** [comment]
This HashSrc is what python script reports. To see what retesteth think is the hash run test with `--showhash` argument. Apparently python can't calculate the hash of your comment. 

```
‘virtual stop’  is parsed as \u2018virtual stop\u2019 by python script.
```

**Comment by matkt** [comment]
> This HashSrc is what python script reports. To see what retesteth think is the hash run test with `--showhash` argument. Apparently python can't calculate the hash of your comment.
> 
> ```
> ‘virtual stop’  is parsed as \u2018virtual stop\u2019 by python script.
> ```

oh yes 🤦  thanks, I just modified the comment

**Comment by sr9000** [comment]
@matkt Hi! I'm a new intern.
I implemented subroutine opcodes support for LLLC. Now you can use this pr https://github.com/winsvega/solidity/pull/2 to compile LLLC and write evm code for fillers using opcodes instead bytecode.

**Comment by matkt** [comment]
> @matkt Hi! I'm a new intern.
> I implemented subroutine opcodes support for LLLC. Now you can use this pr [winsvega/solidity#2](https://github.com/winsvega/solidity/pull/2) to compile LLLC and write evm code for fillers using opcodes instead bytecode.

I just used your update to use the LLLC code. there are two tests that I have not changed because the compiler adds a `STOP` at the end automatically and the goal of the test is to test without STOP at the end.
 - `beginSubAtEndOfCode`
- `subroutineAtEndOfCode`

I also changed the code of the `twoLevelsSubroutines` test because the generated bytecode became different from the original testcase bytecode (optimization) and it was necessary to update the destination of the jumpsub
   - Expected `0x6800000000000000000c5e005c60115e5d5c5d`
   - After LLC compilation of `(asm 0x00000000000000000c JUMPSUB STOP BEGINSUB 0x11 JUMPSUB RETURNSUB BEGINSUB RETURNSUB)"` -> `0x600c5e005c60115e5d5c5d00`

  - The value i'm going to use  : `(asm 0x04 JUMPSUB STOP BEGINSUB 0x09 JUMPSUB RETURNSUB BEGINSUB RETURNSUB)` -> `0x60045e005c60095e5d5c5d00`

**Comment by winsvega** [comment]
Thats are important comments. Worth adding to the filler around lll code. Thanks

**Pull request merged**
