### PR TITLE
Template creator and three tests that use it

### LINKED ISSUE #848: more tests around SELFBALANCE
we have a contribution but I think this needs to be covered more

btw. lllc supports it

### PR DESCRIPTION
**Pull request by qbzzt**
1. `GASPRICE` in multiple contexts
2. `SELFBALANCE` in multiple contexts
3. An invalid opcode (0xFE) in multiple contexts

The contexts are:

//  0. 0x0000  Normal execution
//  1. 0x00F1  CALL a contract with the code
//  2. 0x00F2  CALLCODE a contract ...
//  3. 0x00F4  DELEGATECALL a contract ...
//  4. 0x00FA  STATICCALL a contract ...
//  5. 0xF1F1  CALL a contract that CALLs a contract ...
//  6. 0xF2F1  CALLCODE a contract that CALLs ...
//  7. 0xF4F1  DELEGATECALL ... CALL
//  8. 0xFAF1  STATICCALL ... CALL
//  9. 0xF1F2  CALL a contract that CALLCODEs a contract ...
// 10. 0xF2F2  CALLCODE a contract that CALLCODEs ...
// 11. 0xF4F2  DELEGATECALL ... CALLCODE
// 12. 0xFAF2  STATICCALL ... CALLCODE
// 13. 0xF1F4  CALL a contract that DELEGATECALLs a contract ...
// 14. 0xF2F4  CALLCODE a contract that DELEGATECALLs ...
// 15. 0xF4F4  DELEGATECALL ... DELEGATECALL
// 16. 0xFAF4  STATICCALL ... DELEGATECALL
// 17. 0xF1FA  CALL a contract that STATICCALLs a contract ...
// 18. 0xF2FA  CALLCODE a contract that STATICCALLs ...
// 19. 0xF4FA  DELEGATECALL ... STATICCALL
// 20. 0xFAFA  STATICCALL ... STATICCALL
// 21. 0x00FD  Run the code, call a contract that reverts, then run again
// 22. 0x00FE  Run the code, call a contract that goes out of gas, then run again
// 23. 0x00FF  Run the code, call a contract that self-destructs, then run again
// 24. 0x00F0  CREATE a contract, run the code in the constructor
// 25. 0x00F5  CREATE2 a contract, run the code in the constructor
// 26. 0xF0F1  CREATE a contract with the code and then CALL it
// 27. 0xF5F1  CREATE2 a contract with the code and then CALL it
// 28. 0x60BACCFA57 CALL 1023 times and then run the code at the very end of the call stack

### CODE REVIEW

**Comment by qbzzt** [comment]
Should add a case where the call is recursive, 1023 depth (the maximum before it dies).

**Comment by qbzzt** [comment]
I think we should just merge this now, and add basefee and the other invalid opcodes later when Yul 0.8.5 is available.

**Comment by winsvega** [comment]
so here is a lot of transactions because of data.

so if we want to add a new opcode it will go to the same template?

**Comment by qbzzt** [comment]
Replaced by #882

**Pull request closed without merging**
