### PR TITLE
Fix tests for EIP-3860

### PR DESCRIPTION
**Pull request by gumb0**
Implementation used https://github.com/ethereum/go-ethereum/pull/23847/commits/805e691a0ac26308fd7e0b96b6aeebcd941e9890

Required error definition in retesteth
```
      "TR_InitCodeLimitExceeded" : "max initcode size exceeded",
```

### CODE REVIEW

**Comment by winsvega** [comment]
@gumb0 ready?

**Comment by chfast** [comment]
> Required error definition in retesteth
> 
> ```
>       "TR_InitCodeLimitExceeded" : "max initcode size exceeded",
> ```

Still needed?

**Comment by gumb0** [comment]
> > Required error definition in retesteth
> > ```
> >       "TR_InitCodeLimitExceeded" : "max initcode size exceeded",
> > ```
> 
> Still needed?

I think so, it is used in `creationTxInitCodeSizeLimitFiller.yml`

**Review by chfast — APPROVED** [review]
Looks good from evmone side.

**Pull request merged**
