### PR TITLE
Have operations go OOG with different amounts

### LINKED ISSUE #909: Add test for CREATE2 init code hashing OOG
Add a test with CREATE2 where OOG happens directly because of the cost of hashing the init code.

image

### PR DESCRIPTION
**Pull request by qbzzt**
As requested in #909 to cover the specific case in CREATE2 where the hashing
causes OOG

Closing: 909

### CODE REVIEW

**Comment by chfast** [comment]
This covers the case from #909.

**Comment by qbzzt** [comment]
> This covers the case from #909.

Thank you. Do you have any related cases that you think we can also cover which it doesn't?

**Comment by chfast** [comment]
> Do you have any related cases that you think we can also cover which it doesn't?

Only #910 left.

**Comment by winsvega** [comment]
ready?

**Comment by qbzzt** [comment]
Yes

**Pull request merged**
