### PR TITLE
Remove TransactionNonceCheck from GeneralStateTests

### PR DESCRIPTION
**Pull request by germsvel**
Resolves https://github.com/ethereum/tests/issues/504

What changed?
=============

Removes `TransactionNonceCheck` from `GeneralStateTests/stTransactionTest`

Why?
====

The `TransactionNonceCheck` test never passes the intrinsic validity required of a transaction outlined at the beginning of Section 6 of the YP, since the sender's nonce and the transaction's nonce are different. Because of that, this transaction should not execute at all, and for that reason, it does not make for a good state test. State tests should not have tests with invalid transactions

### CODE REVIEW

**Comment by holiman** [comment]
>  State tests should not have tests with invalid transactions

I whole-heartedly disagree. Where does that come from?

As opposed to blocktests, which are _incapable_ of proving that a transaction is rejected, a statetest is a perfect format to ensure that a certain transaction is properly rejected.

**Comment by germsvel** [comment]
@holiman that's a great point. I was going off a conversation that I had on gitter, so I could be totally wrong. I'm not sure if I can link to the gitter conversation in https://gitter.im/ethereum/tests, but I'll just copy that part of the messages,

> German Velasco @germsvel Sep 10 11:27
I have another question for a different test. Does anybody know why https://github.com/ethereum/tests/blob/develop/src/GeneralStateTestsFiller/stTransactionTest/TransactionNonceCheckFiller.json creates the beneficiary's account before EIP 158? The pre section does not have it, but the post section does. It seems to me that since the account nonce is 10 and the transaction nonce is 0, the transaction never gets executed because it fails step (3) of the initial tests of intrinsic validity.

> Eth-Gitter-Bridge @Eth-Gitter-Bridge Sep 10 11:33
[W Dimitry] Actually wrong nonce transaction is smth that we could check via rpc or forged block tests. **The state tests should not have invalid transactions**
[W Dimitry] How to get a list of transactions with gasprice = 0 in the main chain that has been executed?

> German Velasco @germsvel Sep 10 11:38
I don't know how to get that list of transactions
Are you saying https://github.com/ethereum/tests/blob/develop/src/GeneralStateTestsFiller/stTransactionTest/TransactionNonceCheckFiller.json should not be something we test in state tests? Should I open an issue regarding that?

> Eth-Gitter-Bridge @Eth-Gitter-Bridge Sep 10 11:50
[W Dimitry] Already have an issue about that somewhere

> German Velasco @germsvel Sep 10 11:53
Oh no! I just opened an issue ethereum/tests#504. I'll close it , saying its a duplicate. Do you know which issue it was so I can link to it?

> Eth-Gitter-Bridge @Eth-Gitter-Bridge Sep 10 11:55
[W Dimitry] ethereum/tests#203
[W Dimitry] Yes. Perhaps not exactly like this. You could open a new one
[W Dimitry] But I think such tests should be deleted
[W Dimitry] The transaction is not on real env (parsed by test tool) the blocks frim such tests are just empty blocks

**Comment by winsvega** [comment]
when testing a wrong transaction in state tests it is a test parser tool that check a transaction.
when testing a wrong transaction in bc tests it is most certainly a block validation function that should detect a wrong nonce transaction

**Comment by winsvega** [comment]
The schema check is red. Looks like you forgot to remove some file. 
But we have to delay this PR. We discussed with holiman on skype;


> Because we dont have spare time to move those tests into blockchain and you say its ok to leave incorrect transaction check to state tests parsers I will have to leave those tests. 
> 
> But I say I would prefere to remove all incorrect transaction tests from state tests and make blockchain tests out of them. 
> 
> From the other side if you say all clients has to implement state tests parsers (which I think should not be the case. clientss should implement RPC test methods) if clients implement test RPC methods retesteth will be able to run StateTests/BlockchainnTests + future tests without need for a client to change the parser

**Comment by germsvel** [comment]
I'm closing this for now. I think after understanding https://github.com/ethereum/tests/issues/513, this PR seems like the wrong approach.

**Comment by winsvega** [comment]
@holiman  suggested to keep such option (invalid transaction) in the StateTests. 
we decided to keep it.

**Comment by germsvel** [comment]
Yeah, I think keeping them makes a lot of sense. 

The original impetus for me opening up this PR (and the associated issue #504) was that I couldn't understand how some state tests were expected to pass when they failed intrinsic validity before the transaction was even ran, while still creating the coinbase account (and thus having a changed state root). 

After some research, I discovered that the miner reward and possible clean up of an empty coinbase account need to be simulated in state tests. That is not documented anywhere in the docs, so I opened up https://github.com/ethereum/tests/issues/513.

But I agree that we should keep invalid transaction tests.

**Pull request closed without merging**
