### PR TITLE
Gray Glacier (EIP-5133) Difficulty Bomb Push Fork Tests

### PR DESCRIPTION
**Pull request by marioevz**
This PR is adds new tests for the difficulty bomb push fork Gray Glacier expected in block 15,050,000 (~June 29, 2022).

Tests have not been filled yet since t8ntool support is required.

Execution Spec PR: https://github.com/ethereum/execution-specs/pull/537
EIP-5133: https://eips.ethereum.org/EIPS/eip-5133

### CODE REVIEW

**Comment by marioevz** [comment]
Requires https://github.com/ethereum/go-ethereum/issues/25079

**Comment by winsvega** [comment]
when this happen on mainnet ?

**Comment by marioevz** [comment]
> when this happen on mainnet ?

Current estimate here https://github.com/ethereum/execution-specs/pull/537/files is block 15,050,000 (June 29, 2022).

**Comment by marioevz** [comment]
Filled and ran tests using https://github.com/ethereum/go-ethereum/pull/25088, https://github.com/ethereum/retesteth/pull/169
All tests passing, and also double-checked by calculating the expected difficulty using a separate script on the filled tests (https://github.com/marioevz/eth_tools/blob/main/src/runFilledDiffTest.py).

**Pull request merged**
