### PR TITLE
Invalid and EIP1559 fields to blockchain tests [DOCS]

### PR DESCRIPTION
**Pull request by qbzzt**

### CODE REVIEW

**Comment by winsvega** [comment]
what about new eip1559 formats?

**Comment by qbzzt** [comment]
I'll add them separately. You're right - I forgot about them.

**Comment by winsvega** [comment]
in different pr?

**Comment by qbzzt** [comment]
Yes, if you want to merge this one already.

**Comment by winsvega** [comment]
ready?

**Comment by qbzzt** [comment]
> ready?

Yes, ready, I just forgot to relabel.

**Pull request merged**
