### PR TITLE
Improvements to Test Schema Linting

### PR DESCRIPTION
**Pull request by jwasinger**
**WIP**
Need to get this working and make changes to make the schema more strict.  Part of this will be to add an additional step to the linting script which strips comments from tests before linting them (JSONSchema doesn't have a way to mark fields which are comments).

### CODE REVIEW

**Comment by pirapira** [comment]
I take this over.  Seems straightforward.

**Comment by jwasinger** [comment]
Thanks

**Comment by winsvega** [comment]
what is this about?

**Comment by pirapira** [comment]
@winsvega it's about a stricter schema https://github.com/ethereum/tests/pull/367/commits/12f89dbb67710780370ddf21ce3702ef8059d547

The rest is just fixing formats for the new schema.

**Pull request merged**
