### PR TITLE
constantinople transition test

### PR DESCRIPTION
**Pull request by winsvega**
difficulty change test
reward change test

### CODE REVIEW

**Comment by lithp** [comment]
I'm trying to draw up some release notes and don't know what to say about this PR, this test didn't include a comment! What is this test testing for?

**Comment by winsvega** [comment]
please read the PR description

**Comment by holgerd77** [comment]
@winsvega to give such a self-referencing answer for someone asking for clarification is not sufficient. Please give a better explanation what's going on here.

**Comment by holgerd77** [comment]
(or do you mean another description then these few words

```
difficulty change test
reward change test
```

description from above and I just haven't found?)

**Comment by winsvega** [comment]
Its a transition test to check that rules of a hardfork are activated at transition fork block. I did also tried to test difficulty and reward change for blocks including/not includeing uncles aftet transition point.

**Pull request merged**
