### PR TITLE
Fix storage position to be valid quantities

### PR DESCRIPTION
**Pull request by gsalgado**
According to the spec[1], quantities should not have leading zeroes
after the 0x prefix. Although most clients don't seem to care about
that, pyethapp does.

[1] https://github.com/ethereum/wiki/wiki/JSON-RPC

### CODE REVIEW

**Comment by winsvega** [comment]
I will have to change testeth for that. as the tests are being overwritten

**Comment by winsvega** [comment]
there is a discussion about this issue 
https://github.com/ethereum/EIPs/issues/633

**Comment by pirapira** [comment]
The storage index is a 256-bit word, not an integer.

**Comment by pirapira** [comment]
Closing as this PR edits automatically generated files manually.

**Pull request closed without merging**
