### PR TITLE
Add missing '0's in calldata.  The hex strings were of odd length

### PR DESCRIPTION
**Pull request by pirapira**

### CODE REVIEW

**Comment by winsvega** [comment]
I should check that after this change test is working

**Comment by pirapira** [comment]
I realize I forgot the --checkstate option when I did filling.

**Comment by pirapira** [comment]
I'm going to file a related cpp pull-request.  So you might want to wait for that.

**Comment by pirapira** [comment]
There are many more similar odd-length strings.

**Comment by pirapira** [comment]
https://github.com/ethereum/cpp-ethereum/pull/4185 is the corresponding cpp-ethereum PR.

**Pull request merged**
