### PR TITLE
vmArithmetic tests made into GeneralStateTests

### PR DESCRIPTION
**Pull request by qbzzt**

### CODE REVIEW

**Comment by holgerd77** [comment]
Nice. 😄

**Comment by winsvega** [comment]
This a great start to review all the VM tests that we had unmaintained for a long time. 
not only we put them in the same format as other tests but add more edge cases.

**Comment by winsvega** [comment]
readt to merge first part ?

**Comment by qbzzt** [comment]
> readt to merge first part ?

Yes. It started as vmArithmetic, but now it has a lot of other ones too. The ones that are here are ready.

Well, kind of ready. The unready part is I don't have the filled versions in the repository, but that will be easiest to do after you add the test suites and I can just run them in place.

**Comment by winsvega** [comment]
new tests are supported by new retesteth, currently in develop branch

**Pull request merged**
