### PR TITLE
add test for returndatasize after ecrec

### PR DESCRIPTION
**Pull request by cdetrio**
Minimal test case for consensus issue was discovered by fuzz testing.  Fixed in Parity in https://github.com/paritytech/parity/pull/6652

### CODE REVIEW

**Comment by winsvega** [comment]
please refill with latest develop

**Comment by cdetrio** [comment]
will there be any change with latest develop? other than the `filledwith` metadata

**Comment by winsvega** [comment]
hash of the test filler required

**Comment by pirapira** [comment]
@cdetrio otherwise, when `testeth:develop` runs this test, it reports errors about missing fillerhash.  `testeth:develop` tries to make sure the test is up-to-date with the filler, by comparing the filler contents against a hash recorded in the filled test.

**Comment by winsvega** [comment]
https://github.com/ethereum/tests/pull/362

**Pull request closed without merging**
