### PR TITLE
Reduce balances in SHA3 tests

### PR DESCRIPTION
**Pull request by shemnon**
Reduce the balances in some SHA3 vm tests from 2^256-1 to 2^248-1 to
avoid issues relating to UInt256 rollover.

Signed-off-by: Danno Ferrin <danno.ferrin@gmail.com>

### CODE REVIEW

**Comment by winsvega** [comment]
I actually find it an interesting case. do we have a balance limit officially? 
YP says it can be u256.
do we have a protocol overflow behaviour?

**Comment by shemnon** [comment]
No formal one, but several informal:
* Both OpenEtherem and Besu fail because we use UInt256 for value.
* The BALANCE operation in the EVM will truncate to the lower 256 bits
* Most persuasive, the reference tests themselves truncates to 256 bits in it's post conditions: https://github.com/ethereum/tests/pull/688/files#diff-ce232a19b558d3780ea5e8ed874f05e7R106
  * (geth passes this test!)

**Comment by shemnon** [comment]
As for the travis failures, I have no idea why the source hash is failing.  Do I need to use a newer build of retesteth?

**Comment by winsvega** [comment]
The failures are testeth version of VMTests. I can update those.

**Comment by holiman** [comment]
> The failures are testeth version of VMTests. I can update those.

Did  you already or will you, @winsvega ?

**Review by holiman — APPROVED** [review]

**Comment by shemnon** [comment]
Where can on find and build a current version of testeth from scratch?  Ideally on mac.

**Comment by winsvega** [comment]
Its in ethereum aleth repo

**Comment by winsvega** [comment]
Hold on, we actually have a new intern to be able to do this )
@sr9000

**Comment by sr9000** [comment]
Be patient, I'll working on it.

**Comment by holiman** [comment]
> I actually find it an interesting case. do we have a balance limit officially?

In any case, if it's worthwhile to have a test for the "unofficial gas limit", then that test should be called e.g. `TestGasAboveUint64` and `TestGasAboveInt63` etc. It's odd/quirky to have tests which doesn't match the actual description.

**Comment by sr9000** [comment]
@holiman please, check pr to your repository. All tests passed successfully.

**Comment by adria0** [comment]
> > I actually find it an interesting case. do we have a balance limit officially?
> 
> In any case, if it's worthwhile to have a test for the "unofficial gas limit", then that test should be called e.g. `TestGasAboveUint64` and `TestGasAboveInt63` etc. It's odd/quirky to have tests which doesn't match the actual description.

What about the https://eips.ethereum.org/EIPS/eip-1985? It will be nice to have something like this in this cases.

**Comment by sr9000** [comment]
> What about the https://eips.ethereum.org/EIPS/eip-1985? It will be nice to have something like this in this cases.

@adria0 
Did evm already deal with fields overflow? I see explicit field ranges as part of guaranteed termination/flag setting behavior in such scenarios.

**Comment by adria0** [comment]
@sr9000, it deals in a very explicit way, arithmetic operations are prefixed with `saturating_`,  `checked_` or `overflowing_`, where mainly all types are U256. But not sure, am I answsering your question?

**Comment by shemnon** [comment]
So... what's on travis doesn't like berlin?  Will aleth/testeth get berlin cofings?

**Comment by winsvega** [comment]
There is additional .py script layer that verify the test schema. Apparently it checks that Berlin is in allowed list. It isbin json schema folder

**Comment by shemnon** [comment]
So it turns out these are not even my failure. #685 was merged in with broken tests.  I'm finding the whole process of trying to contribute reference test very frustrating between the lack of follow up and the lack of consistency.

**Comment by shemnon** [comment]
I fixed the travis bits to add Berlin.  But now the subroutine hashes in that PR are wrong. Because #685 was merged when the build was red.

**Comment by sr9000** [comment]
> @sr9000, it deals in a very explicit way, arithmetic operations are prefixed with `saturating_`, `checked_` or `overflowing_`, where mainly all types are U256. But not sure, am I answsering your question?

@adria0 yes, you do, thanks!

**Comment by winsvega** [comment]
> I fixed the travis bits to add Berlin. But now the subroutine hashes in that PR are wrong. Because #685 was merged when the build was red.

yeah, sorry it is a bit chaotic at this moment. with all new test suites and new fork name. 
merged:
https://github.com/ethereum/tests/pull/695

those .py scripts are the second layer that detects issues in tests: such as if test is not generated from filler (hash check).

**Pull request closed without merging**
