### PR TITLE
Blockchain test format doc updates on seal engine type

### PR DESCRIPTION
**Pull request by holgerd77**
Solves issues raised on https://github.com/ethereum/tests/issues/530.

### CODE REVIEW

**Comment by winsvega** [comment]
could you also note that this field is optional and there are still tests without "sealEngine" filed. 
such tests are equvalent to "sealEngine" : "NoProof"

**Comment by holgerd77** [comment]
Ok, will do.

**Comment by holgerd77** [comment]
Ok, just updated and added an additional note on this.

**Comment by holgerd77** [comment]
Can this be merged now?

**Pull request merged**
