### PR TITLE
Template Tests

### LINKED ISSUE #845: Some ideas for more tests with invalid bytes
1. Creation transactions deploying a contracts with all possible values in a first byte, similar to tests for `CREATE` in https://github.com/ethereum/tests/pull/843 (probably will require a blockchain test for this)

2. Init codes starting with a byte with all possible values
2.1. In creation transaction (one invalid byte value is checked in https://github.com/ethereum/tests/pull/842)
2.2. in the code passed to CREATE 
2.3 in the code passed to CREATE2

### LINKED ISSUE #848: more tests around SELFBALANCE
we have a contribution but I think this needs to be covered more

btw. lllc supports it

### PR DESCRIPTION
**Pull request by qbzzt**
Including tests for all the invalid opcodes (there are about a hundred of them).

This replaces #882 (and #856). Dimitry's requests from today are added.

### CODE REVIEW

**Comment by winsvega** [comment]
does this have an update after our call discussion?

**Comment by qbzzt** [comment]
> does this have an update after our call discussion?

Yes, it has everything we discussed.

**Comment by qbzzt** [comment]
It was just easier to start a new PR

**Comment by holiman** [comment]
See https://github.com/ethereum/tests/blob/develop/BlockchainTests/GeneralStateTests/stBadOpcode/invalidDiffPlaces.json#L28 

```
            "uncleHash" : "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
            "baseFee" : "0x0b"
        },
```
Should be `baseFeePerGas`, not `baseFee`. So a lot of these tests fail on go-ethereum on hive due to that.

**Pull request merged**
