### PR TITLE
Try not only RETURNDATASIZE but also RETURNDATACOPY

### PR DESCRIPTION
**Pull request by pirapira**
This implements
https://docs.google.com/spreadsheets/d/1xat7UI8GtB4ZGVdlK5_XQSHJZaMThi4SrlcL8XMZb5Q/edit#gid=1605675414&range=C59

### CODE REVIEW

**Comment by winsvega** [comment]
I guess this was implemented in https://github.com/ethereum/tests/pull/375

(init code) is for transaction init code. testeth now supports lll compilation in trnsaction data field.

**Comment by pirapira** [comment]
Oh I see.

But how do I call RETURNDATACOPY after a create transaction?  In an another transaction?

**Comment by winsvega** [comment]
the idea was to run CREATE opcode from transaction init code. then it is the same.
just put the code from contract to transaction data. it will run it during transaction execution from a new account that is being created. 
you could check storage of this new account.

**Comment by pirapira** [comment]
I see.  That's an interesting test case.

**Pull request closed without merging**
