### PR TITLE
Snark test filled

### PR DESCRIPTION
**Pull request by pirapira**
This is a PR for the elliptic curve related tests.

### CODE REVIEW

**Comment by pirapira** [comment]
This cannot be merged until https://github.com/ethereum/cpp-ethereum/pull/3587 is merged, I heard.

**Comment by chfast** [comment]
Please rebase this, becase we have a conflict in cpp-ethereum.

**Comment by pirapira** [comment]
@chfast rebased this.  I leave the submodule updating to you.

**Comment by winsvega** [comment]
waiting for the cpp branch

**Comment by chfast** [comment]
These need rebase again, but not sure what the base point we should choose.

**Comment by pirapira** [comment]
I'll look at `gitk` and think.

**Comment by chfast** [comment]
It looks we can use the top develop, but the following tests have to be refilled:
```
/home/chfast/Projects/ethereum/cpp-ethereum/test/tools/libtesteth/ImportTest.cpp(603): error: in "StateTestsGeneral/stStaticCall": static_CallEcrecover0_0input Expected another postState hash! expected: 0x75887223f82ad361cc605efc418c8c6102d0e7764cebe727326e07eaa9f508cd actual: de7533eb5b5755c5716216a5af1efb01956d31c58cf0320af5a3b7459e7b8a54 in Metropolis data: 6 gas: 0 val: 0
/home/chfast/Projects/ethereum/cpp-ethereum/test/tools/libtesteth/ImportTest.cpp(603): error: in "StateTestsGeneral/stStaticCall": static_CallEcrecover0_0input Expected another postState hash! expected: 0x75887223f82ad361cc605efc418c8c6102d0e7764cebe727326e07eaa9f508cd actual: a5e31ee199e2bcb29ec91bcdfa7f12fb60afdab24f6a603e85dcd255fa6e0878 in Metropolis data: 7 gas: 0 val: 0
/home/chfast/Projects/ethereum/cpp-ethereum/test/tools/libtesteth/ImportTest.cpp(603): error: in "StateTestsGeneral/stStaticCall": static_CallEcrecover0_0input Expected another postState hash! expected: 0x75887223f82ad361cc605efc418c8c6102d0e7764cebe727326e07eaa9f508cd actual: 9de823ff33e4edd133a73db899d5a4741c247c8c2c9f10235f4c652b6b2abb49 in Metropolis data: 8 gas: 0 val: 0
```

**Comment by pirapira** [comment]
@winsvega ready to merge?  The C++ PR has been merged.

**Pull request merged**
