### PR TITLE
General Transaction Tests

### PR DESCRIPTION
**Pull request by winsvega**

### CODE REVIEW

**Comment by pirapira** [comment]
Did Travis in cpp-ethereum already try the new tests?

**Comment by winsvega** [comment]
yes

**Comment by winsvega** [comment]
its this one https://github.com/ethereum/cpp-ethereum/pull/4664

**Comment by pirapira** [comment]
Why are 10k lines removed while only 8k are added?

**Comment by winsvega** [comment]
I've removed unneeded copies of the tests. a general test describe filler once and then the final test has results on each fork

before I had to copy each test case for new fork. now all testcases are executed on all forks by default

**Pull request merged**
