### PR TITLE
create2 collision tests

### PR DESCRIPTION
**Pull request by winsvega**
Tests for Create2 opcode. 
The list: 
https://docs.google.com/spreadsheets/d/1xat7UI8GtB4ZGVdlK5_XQSHJZaMThi4SrlcL8XMZb5Q/edit?pli=1#gid=1872446916

### CODE REVIEW

**Comment by cburgdorf** [comment]
@winsvega are these test cases already based on the [latest address format](https://github.com/ethereum/EIPs/pull/1014#issuecomment-412106601) that was decided in the last core dev call?

**Comment by winsvega** [comment]
Yes

**Comment by holgerd77** [comment]
Cool! 👍 Can we please please always have the "comment" field filled out on new tests?

**Comment by winsvega** [comment]
Yes. Thanks for mentioning it

**Pull request merged**
