### PR TITLE
Update EOF validation test after TXCREATE removal

### PR DESCRIPTION
**Pull request by chfast**

### CODE REVIEW

**Comment by winsvega** [comment]
rebase

**Review by gumb0 — APPROVED** [review]

**Comment by chfast** [comment]
This is rebased. Can we merge this?

**Comment by chfast** [comment]
Rebased with exception name from EEST.

**Comment by jochem-brouwer** [comment]
This PR is marked to be in https://github.com/ethereum/tests/releases/tag/v14.0, however it is not merged?

**Comment by gumb0** [comment]
> Rebased with exception name from EEST.

I rebased it once again and rolled back this exception name change. This way it is at least consistent with the rest of the file and passes CI (does not require refilling)

@winsvega please check

**Comment by winsvega** [comment]
> This PR is marked to be in https://github.com/ethereum/tests/releases/tag/v14.0, however it is not merged?

My bad I thought it was

**Pull request merged**
