### PR TITLE
New release v7.0.0-beta.1

### PR DESCRIPTION
**Pull request by holgerd77**
Always hoped that the release process would be continued somewhat automatically by the new contributors. Seems that wasn't be the case, so I sat down the evening and compiled down some new release notes myself.

@winsvega @holiman Is this a good time for a new release? Or should I wait for some others PRs to be merged and then update the release notes?

Cheers
Holger

### CODE REVIEW

**Comment by winsvega** [comment]
oh, should I keep the change log with every new PR so making this release notes would be easier ? 

the tests for Istanbul are not finalazied yet.  BlockchainTests would be regenerated. New tests could be added. I would suggest to fnalize the release notes a few days before the actual fork.

**Comment by holgerd77** [comment]
@winsvega Ah, no, we need a release now to start testing, releasing a few days before the fork would be too late. That's what the beta releases should normally before (last time we just didn't made it to the final release 😛). We can do further beta releases if necessary like last time or then do a final `v7.0.0` release once all Istanbul tests are ready.

**Comment by winsvega** [comment]
Ok then. One pr to merge is blake2f tests from shemnon. And it could be a beta release. The branch is develop.

**Comment by holgerd77** [comment]
@winsvega Ok, great! 😄 Now rebased on top of the just merged Blake2bf PR, let me know if anything else is missing.

**Comment by holgerd77** [comment]
Can this be merged now? Or is something missing?

**Comment by winsvega** [comment]
Yes. as a beta.

TODO:
BlockchainTests for istanbul regeneration
TransitionTests
New tests (if any)

**Comment by holgerd77** [comment]
Ah, just saw, #637 is currently probably still a blocker until fixed?

**Comment by winsvega** [comment]
it is fixed.

**Comment by holgerd77** [comment]
Ok, do I still need to update something here? The release is already labeled as a beta.

**Comment by winsvega** [comment]
its fine. it looks pretty descriptive

**Comment by winsvega** [comment]
wait. I found a couple of issues
https://github.com/ethereum/tests/pull/642

**Comment by holiman** [comment]
> oh, should I keep the change log with every new PR so making this release notes would be easier ?

What you should do, imo, is write a detailed description on every PR.

**Comment by gumb0** [comment]
> > oh, should I keep the change log with every new PR so making this release notes would be easier ?
> 
> What you should do, imo, is write a detailed description on every PR.

I think you should do both of these.

**Comment by holgerd77** [comment]
@winsvega Can you also merge here? I don't have sufficient permissions.

**Comment by winsvega** [comment]
Need to remove circle CI error build. It stops the pr from merging from phone

**Comment by holgerd77** [comment]
@winsvega What's the status of this? I interpreted your message on CI from above as something you need to do, is this correct? Or do I need to push again the branch or something or adopt the PR in some way?

**Comment by winsvega** [comment]
No. I just was trying to merge it from the mobile view.

**Comment by holgerd77** [comment]
Ah ok.

**Comment by holgerd77** [comment]
Ok, have done the [release](https://github.com/ethereum/tests/releases/tag/v7.0.0-beta.1) (as always here on the repo as a tag) and posted an associated post on [Reddit](https://www.reddit.com/r/ethereum/comments/dd5hkj/release_v700beta1_for_ethereum_consensus_tests/).

**Comment by holgerd77** [comment]
@winsvega Didn't follow too closely here lately but seems there have been significant PR merges since the last `beta` release regarding `Istanbul` changes like e.g. https://github.com/ethereum/tests/pull/649 and at the same time there are at least atm no significant PRs left open, would it eventually be time for another `beta` release? Then I would prepare some release notes on this.

Or are you eventually even ready that this could be marked as final `Istanbul` release?

**Pull request merged**
