### PR TITLE
Remove RETURNCONTRACT validation tests

### PR DESCRIPTION
**Pull request by gumb0**
These tests are migrated to EEST in https://github.com/ethereum/execution-spec-tests/pull/647

(To keep them here we would need to support "initcode" flag in EOF validation tests, and it seems not worth the effort to do it at this point, it's easier to just remove).

### CODE REVIEW

**Comment by winsvega** [comment]
we have introduced coverage checkup. if you add converted json files to ethereum-converte-tests file in pyspecs. it will measure the coverage of eof tests on pyspec version vs this .json you are about to remove, please try it out.

**Comment by chfast** [comment]
> we have introduced coverage checkup. if you add converted json files to ethereum-converte-tests file in pyspecs. it will measure the coverage of eof tests on pyspec version vs this .json you are about to remove, please try it out.

This doesn't work: https://github.com/ethereum/execution-spec-tests/actions/runs/9715118299

**Comment by winsvega** [comment]
again?
https://github.com/ethereum/execution-spec-tests/pull/657

**Comment by chfast** [comment]
> again? [ethereum/execution-spec-tests#657](https://github.com/ethereum/execution-spec-tests/pull/657)

This is not merged? :shrug:

**Comment by chfast** [comment]
@winsvega Can you make an example migration PR? It looks you made a tool for migration but it is untested.

**Comment by winsvega** [comment]
You mean the coverage?
Its in pyspec repo closed PRs titled TEST 
https://github.com/ethereum/execution-spec-tests/pull/656

**Comment by winsvega** [comment]
> > again? [ethereum/execution-spec-tests#657](https://github.com/ethereum/execution-spec-tests/pull/657)
> 
> This is not merged? :shrug: 
> 

I can't merge without review.

You can just add these changes to your pr.

**Comment by chfast** [comment]
> You can just add these changes to your pr.

I did, but it seems the evmone used is out of date. I'm not sure how to read this report.

**Comment by winsvega** [comment]
the coverage check didn't complete, but its eof tests so let it go. 

```
Error: Contents of /home/travis/build/ethereum/tests/src/EOFTestsFiller/efValidation/EOF1_returncontract_valid_Copier.json is empty. Trying to parse empty file. (forgot --filltests?) (EOFTests/efValidation/EOF1_returncontract_valid_Copier, step: CheckFiller)
Error: 
Error when parsing file (/home/travis/build/ethereum/tests/src/EOFTestsFiller/efValidation/EOF1_returncontract_valid_Copier.json) Contents of /home/travis/build/ethereum/tests/src/EOFTestsFiller/efValidation/EOF1_returncontract_valid_Copier.json is empty. Trying to parse empty file. (forgot --filltests?) 
```

the source and the generated test files must be removed.

**Comment by gumb0** [comment]
> the source and the generated test files must be removed.

fixed

**Pull request merged**
