### PR TITLE
Remove VM tests using the mock BLOCKHASH/BALANCE instruction just for VM tests

### PR DESCRIPTION
**Pull request by pirapira**
See the discussion https://github.com/ethereum/tests/issues/415#issuecomment-378593659

### CODE REVIEW

**Comment by ehildenb** [comment]
@pirapira I believe the following tests also use `BLOCKHASH`
https://github.com/kframework/evm-semantics/commit/dea8f07b92e3c9326da4c55912eed620861d2f54

**Comment by pirapira** [comment]
I'll have a look into these four, and later modify the vmtest runner in `eth-isabelle` so it fails on any `BLOCKHASH`.

**Comment by pirapira** [comment]
Yes, these should be removed too.
* 201503102037PYTHON.json uses `BALANCE`.
* 201503102148PYTHON.json uses `BALANCE`.
* 201503102300PYTHON.json uses `BALANCE`.
* 201503110050PYTHON.json uses `BALANCE`

**Comment by pirapira** [comment]
And then, 201503120317PYTHON.json uses `BALANCE`.

**Comment by pirapira** [comment]
I can detect those VM tests with disallowed instructions using this modified `testeth`. https://github.com/pirapira/testeth/tree/vmtest-filter

**Comment by ehildenb** [comment]
How about also removing the `callcreates` field of the tests?

**Comment by pirapira** [comment]
@ehildenb that's a good idea.  I created a github issue https://github.com/ethereum/tests/issues/449

**Comment by Matthalp-zz** [comment]
@pirapira If you are removing support for `BALANCE` here (and `SELFDESTRUCT` in another PR) do you also want to remove `EXTCODESIZE` and `EXTCODECOPY` too?

They are in this [PR](https://github.com/ethereum/cpp-ethereum/pull/4731/files) that I was (finally) going to come back and try to land this week. Let me know how I should proceed.

**Comment by pirapira** [comment]
@Matthalp yes, `EXTCODE*` is also being removed from VM tests.  If there is a way to fire an error for these instructions in VM tests, that would be nice.

**Comment by Matthalp-zz** [comment]
@pirapira I think https://github.com/ethereum/cpp-ethereum/pull/4731 will fix the ambiguities around `BALANCE`, `EXTCODECOPY`, `EXTDATASIZE`, and `SUICIDE`, but not the `CALL`/`CREATE`s.

Could you help me understand what you mean by "fire an error"? Does this just mean that the test case is able to fail if the incorrect behavior occurs?

**Comment by pirapira** [comment]
Because VM tests are supposed to test one instance of EVM only, and not to access the world state.

**Comment by pirapira** [comment]
Right.  Still VM tests are useful when you are implementing a new VM.

**Pull request merged**
