### PR TITLE
Replaced old tests, added cases

### LINKED ISSUE #939: Test wanted: modexp(0,0, >1)
Looking at https://github.com/ethereum/tests/tree/develop/GeneralStateTests/stPreCompiledContracts, we don't seem to have a modexp-test for `modexp(0,0, nonzero)`.

This is an issue found in py-evm, by @guidovranken

> base = 0
> exponent = 0
> modulo = 36565857650062845505118984243340780147025291371401019
> 
> Geth returns 1, but py-evm returns 0.
> 
> This happens because py-evm returns 0 as soon as it detects that base is 0: https://github.com/ethereum/py-evm/blob/efa07f743db4437a2762dfcd05535177046507e7/eth/precompiles/modexp.py#L96
> which is not correct for any (zero, zero, > 1) tuple for (base, exp, mod).
>

### PR DESCRIPTION
**Pull request by qbzzt**
Closing: #939

### CODE REVIEW

**Comment by winsvega** [comment]
can you make one commit removing old tests
and introduce new tests in other commit. 
preferably filler in a separate commit too

**Comment by qbzzt** [comment]
> can you make one commit removing old tests
> and introduce new tests in other commit.
> preferably filler in a separate commit too

I'll try to remember. Any particular reason?

**Comment by winsvega** [comment]
too many deleted files. I can't find a changed one. even better would be to remove all the files in one PR and introduce a replacement test in another PR

**Comment by qbzzt** [comment]
> 



> too many deleted files. I can't find a changed one.

OK, I'll open a different PR later.

**Comment by qbzzt** [comment]
Replaced by #945

**Pull request closed without merging**
