### PR TITLE
Update vm_tests.rst

### PR DESCRIPTION
**Pull request by feliam**

### CODE REVIEW

**Comment by feliam** [comment]
https://github.com/ethereum/tests/issues/515

**Comment by feliam** [comment]
I think the doc needs at least one decomposed example. Otherwise you would not even know if rlp encoding is the culprit in the case of a mismatch.  Is anyone reading this in possession of such an example ??  Correct [addres, topics, memlog] -> hash  for some test?
 (I 101% prefer the way proposed in the previous doc)

**Comment by feliam** [comment]
nevermind, here it is. For https://github.com/ethereum/tests/blob/develop/VMTests/vmLogTest/log2_nonEmptyMem.json
```
logs = [ (address=0xf572e5295c57f15886f9b263e2f6d2d6c7b5ec6, memlog=b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff'
, topics=(0, 0)) ]
``` 
sha3 of rlp of that is as expected 0x6e02fdc5f0bf3152415cc76a6ed19cd23f9eee9c8ada826de72bfab8c0bbb103.

**Comment by holgerd77** [comment]
Have triggered a rebuild on the docs, section from this PR can be found [here](https://ethereum-tests.readthedocs.io/en/latest/test_types/vm_tests.html#the-logs-section).

**Pull request merged**
