### PR TITLE
fix: file names and references

### PR DESCRIPTION
**Pull request by IaroslavMazur**
Fixed the incorrect file names, as well as the references to them inside the other files in the repo.

### CODE REVIEW

**Comment by winsvega** [comment]
that require test regeneration. do you want me to do it?

**Comment by IaroslavMazur** [comment]
> that require test regeneration. do you want me to do it? 

At this point, I don't (yet) know to do that, so, yes, please!

Also, it'd be awesome if you could briefly explain:
- how the regeneration should be done
- and why it's required in this case, in the first place 🙏🏻

**Comment by winsvega** [comment]
in this repo I track that test source  filler files were used to generate the result test files. 
if you change the filler, hash verification will fail.

**Comment by winsvega** [comment]
https://github.com/ethereum/tests/pull/1393

**Comment by IaroslavMazur** [comment]
> in this repo I track that test source filler files were used to generate the result test files. if you change the filler, hash verification will fail.

Thank you for regenerating the tests! 🙏

**Pull request closed without merging**
