### PR TITLE
Fixed a bug caused by the higher price of a call in Berlin

### PR DESCRIPTION
**Pull request by qbzzt**
Solving the bug in #831 . 

@chfast , can you please verify that this works on your environment and then I'll close the issue, hopefully not prematurely?

   Thanks,
        Ori

### CODE REVIEW

**Comment by chfast** [comment]
First of all, I'm very satisfied how my reports are handled. These are not critical issues and very good process has been made recently. There are still some uncovered cases and I will report these gradually.

In this case, there is still **no hit**. I just realized that in my implementation there are 2 memory checks. First the `RETURNDATACOPY` checks the memory expansion cost. This is covered. But after the memory is successfully expanded, there is additional 3 gas per byte of copying from return data buffer to the memory. The OOG failure at this point is sill not covered.

**Comment by qbzzt** [comment]
As they say in sniper school, "we aim to please". 

> In this case, there is still no hit. I just realized that in my implementation there are 2 memory checks. First the RETURNDATACOPY checks the memory expansion cost. This is covered. But after the memory is successfully expanded, there is additional 3 gas per byte of copying from return data buffer to the memory. The OOG failure at this point is sill not covered.

We don't normally look inside individual opcodes, but I added a test that runs with 3073 gas, one less than the amount actually needed. I hope it fails in the correct place. If it doesn't, please send me a trace so I'll know how much gas to allocate to get the correct failure.

**Comment by chfast** [comment]
This works as expected now. Thanks.

**Comment by qbzzt** [comment]
> This works as expected now. Thanks.

Thank you, I'll close the issue. If you have anything else, ask and we'll try to provide.

**Comment by winsvega** [comment]
why 16k lines removed? just disabling one fork leads to this?

**Comment by qbzzt** [comment]
> why 16k lines removed? just disabling one fork leads to this?

Yes. The file is ~16k for Berlin, and it was ~16k for Instanbul. 

I'll rebase later today after I'm done with dayjob stuff.

**Pull request merged**
