### PR TITLE
Update tests to Shanghai (partially)

### PR DESCRIPTION
**Pull request by rodiazet**
Most of the test are updated to Shanghai. Still a couple of errors listed in attached doc.
Testing on evmone master branch

https://hackmd.io/@etgDMnCFQgS7tnZ9yjkOPw/SylTKkypj

### CODE REVIEW

**Comment by winsvega** [comment]
this is a matter of revisioning each test that failed like this. because need to be sure that the test didn't fail and still works and affected by shanghai in a good way. (gas change, eip interaction)

for this reason there are warning when expect section uses coinbase balance or origin balance checks.

**Comment by rodiazet** [comment]
> this is a matter of revisioning each test that failed like this. because need to be sure that the test didn't fail and still works and affected by shanghai in a good way. (gas change, eip interaction)
> 
> for this reason there are warning when expect section uses coinbase balance or origin balance checks.

Sure. Just wanted to know which tests I didn't update do Shanghai because it probably takes minutes to someone who is more familiar with the generated tests. I hope it's beneficial in any way.

**Comment by winsvega** [comment]
is latest geth master shanghai ready?

**Comment by winsvega** [comment]
in progress. updating all tests to Shanghai. I've checked all of them seems to be no breaking changes. Ori must fix his vectors now.

**Pull request closed without merging**
