### PR TITLE
chore: fix grammar mistakes in index.rst

### PR DESCRIPTION
**Pull request by IaroslavMazur**

### CODE REVIEW

**Comment by Pareek0211** [comment]
sorry. my english is weak.so please forgive me.

**Comment by Pareek0211** [comment]
my english is weak.forgive me

**Comment by holiman** [comment]
Thanks but it's fine as it is

**Comment by holiman** [comment]
Sorry, I actually thought this PR was on a different repo. I'll let someone else make the call for this PR, I don't usually admin this repository :)

**Pull request merged**
