### PR TITLE
stEIP2537

### PR DESCRIPTION
**Pull request by winsvega**

### CODE REVIEW

**Comment by jochem-brouwer** [comment]
Hey there. This PR looks like it only creates tests for Berlin. It is thus not explicitly tested that pre-Berlin one cannot access the EIP 2537 precompiles. Pre-Berlin the storage slot should yield the string of an empty keccak (as the staticcalls will return an empty string, but they will succeed).

**Comment by jochem-brouwer** [comment]
What's also not in these state tests are tests for empty inputs on the G1/G2 multiexponentation and pairing. These should be added. There are also no tests with inputs which do not have the expected length (i.e. the length of the input `mod` some constant is nonzero).

CC @shamatar

**Comment by jochem-brouwer** [comment]
Also what might be a good idea is to add 4 tests for `MapToG1` and `MapToG2` where the `Fp` and `Fp2` points are the `Base field modulus` (error) and `Base field modulus - 1` (no error).

**Comment by shamatar** [comment]
There are negative tests for FpToG1 mapping (I think for Fp2 too) where field element is larger than modulus. You can make extra ones and PR to 1962 repo, there is a code there to make positive/negative tests and dump them to CSV.

**Comment by winsvega** [comment]
source for contract bytecode in fillers or generator script ?

**Comment by shamatar** [comment]
I've posted it in the original PR https://github.com/ethereum/tests/pull/712#issuecomment-656246408

**Comment by winsvega** [comment]
The generator script? The tests txs also contain data.

**Pull request merged**
