### PR TITLE
add 0x prefix to state test transaction data

### PR DESCRIPTION
**Pull request by cdetrio**
This fixes the only state tests missing `0x` from the transaction data field, 19 filler files and 15 test files (the four extra filler files are in `stStaticCallNoStateChange`, which does not have corresponding filled files).

With these fixes, all state tests are passing the JSON schema validator https://github.com/ethereum/tests/pull/213.

### CODE REVIEW

**Comment by cdetrio** [comment]
update: the JSON schema now has storage restrictions. so https://github.com/ethereum/tests/pull/254 is now needed too for all state tests to pass the schema validator.

**Comment by winsvega** [comment]
As you changed the fillers. have you tried to run testeth --filltests on those changed tests? 
if there are errors please let me know.

**Comment by pirapira** [comment]
However, if you use `cpp-ethereum:develop` now, the `0x`s will disappear.  https://github.com/ethereum/cpp-ethereum/pull/4366 has to be merged first.

**Comment by pirapira** [comment]
Now `cpp-ethereum:develop` should not remove `0x`s.

**Comment by pirapira** [comment]
I started what I requested.

**Comment by pirapira** [comment]
`test/testeth -t StateTestsGeneral -- --filltests` showed me only failures unrelated to this PR.

**Pull request merged**
