### PR TITLE
Test validator script

### PR DESCRIPTION
**Pull request by ehildenb**
Subsuming #465 and #461 .

### CODE REVIEW

**Comment by ehildenb** [comment]
I've also disabled the json validity checks that .travis.yml was doing because ./test.py does them anyway.

**Comment by winsvega** [comment]
same here. if it touches only VMTests merge at @pirapira  approval

**Comment by pirapira** [comment]
I skimmed commit by commit.  Not quite only VMTests, but looks good.

**Comment by pirapira** [comment]
Let me break some test files locally and see what the new validator does.

**Pull request merged**
