### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by rex4539**

### CODE REVIEW

**Comment by rex4539** [comment]
@winsvega Could you please take a look?

**Comment by winsvega** [comment]
hm. can you split it to multiple PRs? 
1) docs and legacy tests (the one that does not need a refill)
2) EIPTests  (tricky one beacuse to refill it need banches of WIP )
3) EOFTests  
4) BC/State tests that need a refill.

**Comment by rex4539** [comment]
I have no idea how to do this as I'm not very familiar with the git command line args.

If you can type out the exact commands I need to type, I would be happy to do it right now.

**Comment by rex4539** [comment]
That's what I figured.

**Pull request closed without merging**
